nome = str(input('digete seu nome completo?')).strip()
print('seu nome maiusculo ficou:', nome.upper())
print('seu nome minusculo ficou:', nome.lower())
print('seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
print('seu primeiro nome tem {} letras'.format(nome.find(' ')))